[package]
name = "goat"
version = "0.1.3"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.0"
reqwest = "0.11.5"
tokio = { version = "1.12.0", features = ["full"] }
lazy_static = "1.4.0"
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3.17"
again = "0.1"